services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    # environment:
    #   - SKIP_MODEL_LOAD=1
    volumes:
      - .:/app
      - ./keys:/app/keys:ro        # GCP TTS 인증 키
      - ./output:/app/output    # 결과물 캐시
