services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    gpus: all
    
    ports:
      - "8000:8000"
    # env_file:
    #   - .env
    # # environment:
    # #   - SKIP_MODEL_LOAD=1
    # volumes:
    #   - .:/app
    #   - ./keys:/app/keys:ro        # GCP TTS 인증 키
    #   - ./output:/app/output    # 결과물 캐시
    environment:
      - OPENAI_API_KEY
      - GOOGLE_APPLICATION_CREDENTIALS=/app/app/data/keys/tts.json
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - S3_BUCKET
      - BE_SERVER_URL

    volumes:
      # - ./output:/app/output
      # - ./keys:/app/keys:ro 
      - ./app/data:/app/app/data 